/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as GenresRouteImport } from './routes/genres'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CountriesCountryCodeRouteImport } from './routes/countries.$countryCode'
import { Route as GenresGenreSlugRouteImport } from './routes/genres.$genreSlug'
import { Route as StationsStationIdRouteImport } from './routes/stations.$stationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresRoute = GenresRouteImport.update({
  id: '/genres',
  path: '/genres',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const CountriesCountryCodeRoute = CountriesCountryCodeRouteImport.update({
  id: '/$countryCode',
  path: '/$countryCode',
  getParentRoute: () => CountriesRoute,
} as any)
const GenresGenreSlugRoute = GenresGenreSlugRouteImport.update({
  id: '/$genreSlug',
  path: '/$genreSlug',
  getParentRoute: () => GenresRoute,
} as any)
const StationsStationIdRoute = StationsStationIdRouteImport.update({
  id: '/stations/$stationId',
  path: '/stations/$stationId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/countries': typeof CountriesRouteWithChildren
  '/genres': typeof GenresRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/countries/$countryCode': typeof CountriesCountryCodeRoute
  '/genres/$genreSlug': typeof GenresGenreSlugRoute
  '/stations/$stationId': typeof StationsStationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/countries': typeof CountriesRouteWithChildren
  '/genres': typeof GenresRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/countries/$countryCode': typeof CountriesCountryCodeRoute
  '/genres/$genreSlug': typeof GenresGenreSlugRoute
  '/stations/$stationId': typeof StationsStationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/countries': typeof CountriesRouteWithChildren
  '/genres': typeof GenresRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/countries/$countryCode': typeof CountriesCountryCodeRoute
  '/genres/$genreSlug': typeof GenresGenreSlugRoute
  '/stations/$stationId': typeof StationsStationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/countries'
    | '/genres'
    | '/blog/$slug'
    | '/countries/$countryCode'
    | '/genres/$genreSlug'
    | '/stations/$stationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/countries'
    | '/genres'
    | '/blog/$slug'
    | '/countries/$countryCode'
    | '/genres/$genreSlug'
    | '/stations/$stationId'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/countries'
    | '/genres'
    | '/blog/$slug'
    | '/countries/$countryCode'
    | '/genres/$genreSlug'
    | '/stations/$stationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  CountriesRoute: typeof CountriesRouteWithChildren
  GenresRoute: typeof GenresRouteWithChildren
  StationsStationIdRoute: typeof StationsStationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres': {
      id: '/genres'
      path: '/genres'
      fullPath: '/genres'
      preLoaderRoute: typeof GenresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/countries/$countryCode': {
      id: '/countries/$countryCode'
      path: '/$countryCode'
      fullPath: '/countries/$countryCode'
      preLoaderRoute: typeof CountriesCountryCodeRouteImport
      parentRoute: typeof CountriesRoute
    }
    '/genres/$genreSlug': {
      id: '/genres/$genreSlug'
      path: '/$genreSlug'
      fullPath: '/genres/$genreSlug'
      preLoaderRoute: typeof GenresGenreSlugRouteImport
      parentRoute: typeof GenresRoute
    }
    '/stations/$stationId': {
      id: '/stations/$stationId'
      path: '/stations/$stationId'
      fullPath: '/stations/$stationId'
      preLoaderRoute: typeof StationsStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CountriesRouteChildren {
  CountriesCountryCodeRoute: typeof CountriesCountryCodeRoute
}

const CountriesRouteChildren: CountriesRouteChildren = {
  CountriesCountryCodeRoute: CountriesCountryCodeRoute,
}

const CountriesRouteWithChildren = CountriesRoute._addFileChildren(
  CountriesRouteChildren,
)

interface GenresRouteChildren {
  GenresGenreSlugRoute: typeof GenresGenreSlugRoute
}

const GenresRouteChildren: GenresRouteChildren = {
  GenresGenreSlugRoute: GenresGenreSlugRoute,
}

const GenresRouteWithChildren =
  GenresRoute._addFileChildren(GenresRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  CountriesRoute: CountriesRouteWithChildren,
  GenresRoute: GenresRouteWithChildren,
  StationsStationIdRoute: StationsStationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
