/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteRouteImport } from './routes/$lang/route'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WhoWeAreRouteImport } from './routes/who-we-are'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangFaqRouteImport } from './routes/$lang/faq'
import { Route as LangPrivacyRouteImport } from './routes/$lang/privacy'
import { Route as LangTermsRouteImport } from './routes/$lang/terms'
import { Route as LangWhoWeAreRouteImport } from './routes/$lang/who-we-are'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CountriesIndexRouteImport } from './routes/countries.index'
import { Route as CountriesCountryCodeRouteImport } from './routes/countries.$countryCode'
import { Route as GenresIndexRouteImport } from './routes/genres.index'
import { Route as GenresGenreSlugRouteImport } from './routes/genres.$genreSlug'
import { Route as StationsStationIdRouteImport } from './routes/stations.$stationId'
import { Route as LangBlogIndexRouteImport } from './routes/$lang/blog.index'
import { Route as LangBlogSlugRouteImport } from './routes/$lang/blog.$slug'
import { Route as LangCountriesIndexRouteImport } from './routes/$lang/countries.index'
import { Route as LangCountriesCountryCodeRouteImport } from './routes/$lang/countries.$countryCode'
import { Route as LangGenresIndexRouteImport } from './routes/$lang/genres.index'
import { Route as LangGenresGenreSlugRouteImport } from './routes/$lang/genres.$genreSlug'
import { Route as LangStationsStationIdRouteImport } from './routes/$lang/stations.$stationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRouteRoute = LangRouteRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WhoWeAreRoute = WhoWeAreRouteImport.update({
  id: '/who-we-are',
  path: '/who-we-are',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangFaqRoute = LangFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangPrivacyRoute = LangPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangTermsRoute = LangTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangWhoWeAreRoute = LangWhoWeAreRouteImport.update({
  id: '/who-we-are',
  path: '/who-we-are',
  getParentRoute: () => LangRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesIndexRoute = CountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesCountryCodeRoute = CountriesCountryCodeRouteImport.update({
  id: '/countries/$countryCode',
  path: '/countries/$countryCode',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresIndexRoute = GenresIndexRouteImport.update({
  id: '/genres/',
  path: '/genres/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresGenreSlugRoute = GenresGenreSlugRouteImport.update({
  id: '/genres/$genreSlug',
  path: '/genres/$genreSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const StationsStationIdRoute = StationsStationIdRouteImport.update({
  id: '/stations/$stationId',
  path: '/stations/$stationId',
  getParentRoute: () => rootRouteImport,
} as any)
const LangBlogIndexRoute = LangBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangBlogSlugRoute = LangBlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCountriesIndexRoute = LangCountriesIndexRouteImport.update({
  id: '/countries/',
  path: '/countries/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangCountriesCountryCodeRoute =
  LangCountriesCountryCodeRouteImport.update({
    id: '/countries/$countryCode',
    path: '/countries/$countryCode',
    getParentRoute: () => LangRouteRoute,
  } as any)
const LangGenresIndexRoute = LangGenresIndexRouteImport.update({
  id: '/genres/',
  path: '/genres/',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangGenresGenreSlugRoute = LangGenresGenreSlugRouteImport.update({
  id: '/genres/$genreSlug',
  path: '/genres/$genreSlug',
  getParentRoute: () => LangRouteRoute,
} as any)
const LangStationsStationIdRoute = LangStationsStationIdRouteImport.update({
  id: '/stations/$stationId',
  path: '/stations/$stationId',
  getParentRoute: () => LangRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/terms': typeof LangTermsRoute
  '/$lang/who-we-are': typeof LangWhoWeAreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/countries/$countryCode': typeof CountriesCountryCodeRoute
  '/genres/$genreSlug': typeof GenresGenreSlugRoute
  '/stations/$stationId': typeof StationsStationIdRoute
  '/$lang/': typeof LangIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/countries/': typeof CountriesIndexRoute
  '/genres/': typeof GenresIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/countries/$countryCode': typeof LangCountriesCountryCodeRoute
  '/$lang/genres/$genreSlug': typeof LangGenresGenreSlugRoute
  '/$lang/stations/$stationId': typeof LangStationsStationIdRoute
  '/$lang/blog/': typeof LangBlogIndexRoute
  '/$lang/countries/': typeof LangCountriesIndexRoute
  '/$lang/genres/': typeof LangGenresIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/terms': typeof LangTermsRoute
  '/$lang/who-we-are': typeof LangWhoWeAreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/countries/$countryCode': typeof CountriesCountryCodeRoute
  '/genres/$genreSlug': typeof GenresGenreSlugRoute
  '/stations/$stationId': typeof StationsStationIdRoute
  '/$lang': typeof LangIndexRoute
  '/blog': typeof BlogIndexRoute
  '/countries': typeof CountriesIndexRoute
  '/genres': typeof GenresIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/countries/$countryCode': typeof LangCountriesCountryCodeRoute
  '/$lang/genres/$genreSlug': typeof LangGenresGenreSlugRoute
  '/$lang/stations/$stationId': typeof LangStationsStationIdRoute
  '/$lang/blog': typeof LangBlogIndexRoute
  '/$lang/countries': typeof LangCountriesIndexRoute
  '/$lang/genres': typeof LangGenresIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteRouteWithChildren
  '/faq': typeof FaqRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/$lang/faq': typeof LangFaqRoute
  '/$lang/privacy': typeof LangPrivacyRoute
  '/$lang/terms': typeof LangTermsRoute
  '/$lang/who-we-are': typeof LangWhoWeAreRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/countries/$countryCode': typeof CountriesCountryCodeRoute
  '/genres/$genreSlug': typeof GenresGenreSlugRoute
  '/stations/$stationId': typeof StationsStationIdRoute
  '/$lang/': typeof LangIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/countries/': typeof CountriesIndexRoute
  '/genres/': typeof GenresIndexRoute
  '/$lang/blog/$slug': typeof LangBlogSlugRoute
  '/$lang/countries/$countryCode': typeof LangCountriesCountryCodeRoute
  '/$lang/genres/$genreSlug': typeof LangGenresGenreSlugRoute
  '/$lang/stations/$stationId': typeof LangStationsStationIdRoute
  '/$lang/blog/': typeof LangBlogIndexRoute
  '/$lang/countries/': typeof LangCountriesIndexRoute
  '/$lang/genres/': typeof LangGenresIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/who-we-are'
    | '/$lang/faq'
    | '/$lang/privacy'
    | '/$lang/terms'
    | '/$lang/who-we-are'
    | '/blog/$slug'
    | '/countries/$countryCode'
    | '/genres/$genreSlug'
    | '/stations/$stationId'
    | '/$lang/'
    | '/blog/'
    | '/countries/'
    | '/genres/'
    | '/$lang/blog/$slug'
    | '/$lang/countries/$countryCode'
    | '/$lang/genres/$genreSlug'
    | '/$lang/stations/$stationId'
    | '/$lang/blog/'
    | '/$lang/countries/'
    | '/$lang/genres/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/who-we-are'
    | '/$lang/faq'
    | '/$lang/privacy'
    | '/$lang/terms'
    | '/$lang/who-we-are'
    | '/blog/$slug'
    | '/countries/$countryCode'
    | '/genres/$genreSlug'
    | '/stations/$stationId'
    | '/$lang'
    | '/blog'
    | '/countries'
    | '/genres'
    | '/$lang/blog/$slug'
    | '/$lang/countries/$countryCode'
    | '/$lang/genres/$genreSlug'
    | '/$lang/stations/$stationId'
    | '/$lang/blog'
    | '/$lang/countries'
    | '/$lang/genres'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/faq'
    | '/privacy'
    | '/terms'
    | '/who-we-are'
    | '/$lang/faq'
    | '/$lang/privacy'
    | '/$lang/terms'
    | '/$lang/who-we-are'
    | '/blog/$slug'
    | '/countries/$countryCode'
    | '/genres/$genreSlug'
    | '/stations/$stationId'
    | '/$lang/'
    | '/blog/'
    | '/countries/'
    | '/genres/'
    | '/$lang/blog/$slug'
    | '/$lang/countries/$countryCode'
    | '/$lang/genres/$genreSlug'
    | '/$lang/stations/$stationId'
    | '/$lang/blog/'
    | '/$lang/countries/'
    | '/$lang/genres/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRouteRoute: typeof LangRouteRouteWithChildren
  FaqRoute: typeof FaqRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  WhoWeAreRoute: typeof WhoWeAreRoute
  BlogSlugRoute: typeof BlogSlugRoute
  CountriesCountryCodeRoute: typeof CountriesCountryCodeRoute
  GenresGenreSlugRoute: typeof GenresGenreSlugRoute
  StationsStationIdRoute: typeof StationsStationIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  CountriesIndexRoute: typeof CountriesIndexRoute
  GenresIndexRoute: typeof GenresIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/who-we-are': {
      id: '/who-we-are'
      path: '/who-we-are'
      fullPath: '/who-we-are'
      preLoaderRoute: typeof WhoWeAreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/faq': {
      id: '/$lang/faq'
      path: '/faq'
      fullPath: '/$lang/faq'
      preLoaderRoute: typeof LangFaqRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/privacy': {
      id: '/$lang/privacy'
      path: '/privacy'
      fullPath: '/$lang/privacy'
      preLoaderRoute: typeof LangPrivacyRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/terms': {
      id: '/$lang/terms'
      path: '/terms'
      fullPath: '/$lang/terms'
      preLoaderRoute: typeof LangTermsRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/who-we-are': {
      id: '/$lang/who-we-are'
      path: '/who-we-are'
      fullPath: '/$lang/who-we-are'
      preLoaderRoute: typeof LangWhoWeAreRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/': {
      id: '/countries/'
      path: '/countries'
      fullPath: '/countries/'
      preLoaderRoute: typeof CountriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries/$countryCode': {
      id: '/countries/$countryCode'
      path: '/countries/$countryCode'
      fullPath: '/countries/$countryCode'
      preLoaderRoute: typeof CountriesCountryCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/': {
      id: '/genres/'
      path: '/genres'
      fullPath: '/genres/'
      preLoaderRoute: typeof GenresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/$genreSlug': {
      id: '/genres/$genreSlug'
      path: '/genres/$genreSlug'
      fullPath: '/genres/$genreSlug'
      preLoaderRoute: typeof GenresGenreSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stations/$stationId': {
      id: '/stations/$stationId'
      path: '/stations/$stationId'
      fullPath: '/stations/$stationId'
      preLoaderRoute: typeof StationsStationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/blog/': {
      id: '/$lang/blog/'
      path: '/blog'
      fullPath: '/$lang/blog/'
      preLoaderRoute: typeof LangBlogIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/blog/$slug': {
      id: '/$lang/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/$lang/blog/$slug'
      preLoaderRoute: typeof LangBlogSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/countries/': {
      id: '/$lang/countries/'
      path: '/countries'
      fullPath: '/$lang/countries/'
      preLoaderRoute: typeof LangCountriesIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/countries/$countryCode': {
      id: '/$lang/countries/$countryCode'
      path: '/countries/$countryCode'
      fullPath: '/$lang/countries/$countryCode'
      preLoaderRoute: typeof LangCountriesCountryCodeRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/genres/': {
      id: '/$lang/genres/'
      path: '/genres'
      fullPath: '/$lang/genres/'
      preLoaderRoute: typeof LangGenresIndexRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/genres/$genreSlug': {
      id: '/$lang/genres/$genreSlug'
      path: '/genres/$genreSlug'
      fullPath: '/$lang/genres/$genreSlug'
      preLoaderRoute: typeof LangGenresGenreSlugRouteImport
      parentRoute: typeof LangRouteRoute
    }
    '/$lang/stations/$stationId': {
      id: '/$lang/stations/$stationId'
      path: '/stations/$stationId'
      fullPath: '/$lang/stations/$stationId'
      preLoaderRoute: typeof LangStationsStationIdRouteImport
      parentRoute: typeof LangRouteRoute
    }
  }
}

interface LangRouteRouteChildren {
  LangFaqRoute: typeof LangFaqRoute
  LangPrivacyRoute: typeof LangPrivacyRoute
  LangTermsRoute: typeof LangTermsRoute
  LangWhoWeAreRoute: typeof LangWhoWeAreRoute
  LangIndexRoute: typeof LangIndexRoute
  LangBlogSlugRoute: typeof LangBlogSlugRoute
  LangCountriesCountryCodeRoute: typeof LangCountriesCountryCodeRoute
  LangGenresGenreSlugRoute: typeof LangGenresGenreSlugRoute
  LangStationsStationIdRoute: typeof LangStationsStationIdRoute
  LangBlogIndexRoute: typeof LangBlogIndexRoute
  LangCountriesIndexRoute: typeof LangCountriesIndexRoute
  LangGenresIndexRoute: typeof LangGenresIndexRoute
}

const LangRouteRouteChildren: LangRouteRouteChildren = {
  LangFaqRoute: LangFaqRoute,
  LangPrivacyRoute: LangPrivacyRoute,
  LangTermsRoute: LangTermsRoute,
  LangWhoWeAreRoute: LangWhoWeAreRoute,
  LangIndexRoute: LangIndexRoute,
  LangBlogSlugRoute: LangBlogSlugRoute,
  LangCountriesCountryCodeRoute: LangCountriesCountryCodeRoute,
  LangGenresGenreSlugRoute: LangGenresGenreSlugRoute,
  LangStationsStationIdRoute: LangStationsStationIdRoute,
  LangBlogIndexRoute: LangBlogIndexRoute,
  LangCountriesIndexRoute: LangCountriesIndexRoute,
  LangGenresIndexRoute: LangGenresIndexRoute,
}

const LangRouteRouteWithChildren = LangRouteRoute._addFileChildren(
  LangRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRouteRoute: LangRouteRouteWithChildren,
  FaqRoute: FaqRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  WhoWeAreRoute: WhoWeAreRoute,
  BlogSlugRoute: BlogSlugRoute,
  CountriesCountryCodeRoute: CountriesCountryCodeRoute,
  GenresGenreSlugRoute: GenresGenreSlugRoute,
  StationsStationIdRoute: StationsStationIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  CountriesIndexRoute: CountriesIndexRoute,
  GenresIndexRoute: GenresIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
